# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  preview:
    open: false
    width: 80
  prsLimit: 25
  issuesLimit: 25
  view: prs
  layout:
    prs:
      repo:
        grow: true
        width: 25
        hidden: false
    issues:
      repo:
        grow: true
        width: 25
        hidden: false
pager:
  diff: less
repoPaths:
  datsfilipe/*: ~/www/s/github.com/datsfilipe/*
keybindings:
  prs:
    - key: O
      command: >
        tmux new-window -c {{.RepoPath}} '
          gh pr checkout {{.PrNumber}} &&
          nvim -c ":DiffviewOpen main...{{.HeadRefName}}"
        '
  issues:
    - key: P
      command: gh issue pin {{.IssueNumber}} --repo {.RepoName}
